//! 04 Safety flags — deterministic, OFFLINE rules with OSHA trade context attached.
//! Rules-first by design (no LLM in the core loop). Flags ASSIST judgment — the user
//! accepts / dismisses / annotates each one. Biased toward recall (catching gaps).
//!
//! v2.2: adds trade-scoped highway/bridge & civil rules (work-zone, struck-by, trench,
//! caught-in, steel erection, electrocution), sourced from OSHA 29 CFR 1926, and surfaces
//! SEVERITY (avg penalty when cited) in the OSHA context, not just the citation rate.
//! ponytail: severity = avg_penalty_per_cited (present in the offline stats). The PRD also
//! mentions "violations per cited", but that count isn't in osha_trade_stats.json and can't be
//! regenerated offline (needs the DOL API pull) — the penalty dollars are the severity signal we
//! have, and they're the PRD's own headline number ($21,700 for highway/bridge).
use serde::Serialize;

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Flag {
    pub code: String,
    pub title: String,
    pub rationale: String,
    pub osha_context: Option<String>,
}

// OSHA trade stats generated by data/osha_pipeline.py (bundled, read fully offline).
const TRADE_STATS: &str = include_str!("../../data/osha_trade_stats.json");

/// "$21,700" — round to the nearest $100 and group thousands with commas.
fn fmt_usd(n: f64) -> String {
    let dollars = ((n / 100.0).round() * 100.0) as i64;
    let digits = dollars.to_string();
    let len = digits.len();
    let mut out = String::with_capacity(len + len / 3);
    for (i, ch) in digits.chars().enumerate() {
        if i > 0 && (len - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(ch);
    }
    format!("${out}")
}

/// Trade context for a flag, from the OSHA data spine. Surfaces both frequency (cited_rate)
/// and severity (avg penalty when cited), e.g.
/// "Highway/Bridge · 41.1% cited · ~$21,700 avg penalty when cited".
pub fn cited_context(naics: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(TRADE_STATS).ok()?;
    let t = v.get("trades")?.get(naics)?;
    let name = t.get("name")?.as_str()?;
    let rate = t.get("cited_rate")?.as_f64()?;
    match t.get("avg_penalty_per_cited").and_then(|x| x.as_f64()) {
        Some(p) if p > 0.0 => Some(format!(
            "{name} · {:.1}% cited · ~{} avg penalty when cited",
            rate * 100.0,
            fmt_usd(p)
        )),
        _ => Some(format!("{name} · {:.1}% cited for this", rate * 100.0)),
    }
}

struct Rule {
    code: &'static str,
    title: &'static str,
    rationale: &'static str,
    keywords: &'static [&'static str],
    /// Empty = fires for every trade. Otherwise fires only when the record's trade
    /// NAICS is in this list (trade-scoped, for civil/highway-specific hazards).
    trades: &'static [&'static str],
}

// Civil trades the highway/bridge-specific rules apply to:
// 237310 Highway/Street/Bridge · 237110 Water/Sewer · 237120 Oil&Gas Pipeline · 237130 Power/Comm line.
const CIVIL: &[&str] = &["237310", "237110", "237120", "237130"];

const RULES: &[Rule] = &[
    // ---- existing global rules (apply to all trades) ----
    Rule {
        code: "FALL",
        title: "Fall protection",
        rationale: "Work at height is described — confirm fall protection (harness/lanyard, guardrail, or net) was in place. OSHA requires it at 6 ft or more (1926 Subpart M).",
        keywords: &[
            "roof", "rooftop", "ladder", "leading edge", "open edge", "off the edge",
            "height", "elevated", "second floor", "third floor", "no harness", "without a harness",
            "deck", "bridge deck",
        ],
        trades: &[],
    },
    Rule {
        code: "PPE",
        title: "PPE",
        rationale: "A missing-PPE phrase was detected — confirm hard hat, eye protection, gloves, and hi-vis as required.",
        keywords: &[
            "no hard hat", "without a hard hat", "no helmet", "no gloves", "without gloves",
            "no goggles", "no glasses", "no eye protection", "no vest", "no hi-vis",
            "without ppe", "missing ppe",
        ],
        trades: &[],
    },
    Rule {
        code: "SCAF",
        title: "Scaffolding / guardrail",
        rationale: "Scaffolding is described — confirm guardrails, proper planking, and a competent-person inspection.",
        keywords: &["scaffold", "guardrail", "planking", "staging", "work platform"],
        trades: &[],
    },
    // ---- highway/bridge & civil rules (sourced: OSHA 29 CFR 1926, FHWA MUTCD) ----
    Rule {
        code: "WORKZONE",
        title: "Work-zone traffic control",
        rationale: "Work next to live traffic is described — confirm a temporary traffic-control plan, flaggers in hi-vis, and proper signs/cones/barriers (OSHA 1926 Subpart G; FHWA MUTCD Part 6).",
        keywords: &[
            "traffic", "work zone", "lane closure", "shoulder", "median", "flagger",
            "cones", "barrels", "live traffic", "motorist", "passing cars", "road closure",
        ],
        trades: CIVIL,
    },
    Rule {
        code: "STRUCKVEH",
        title: "Struck-by / backover (mobile equipment)",
        rationale: "Mobile or heavy equipment is operating near workers — confirm spotters, backup alarms, and that no one was in the swing radius or a blind spot (OSHA 1926.601). Struck-by is the leading roadway-work killer.",
        keywords: &[
            "backing up", "backover", "spotter", "blind spot", "run over", "dump truck",
            "loader", "excavator", "roller", "swing radius", "backed into", "no spotter",
        ],
        trades: CIVIL,
    },
    Rule {
        code: "TRENCH",
        title: "Excavation / trench cave-in",
        rationale: "Excavation is described — a protective system (sloping / shoring / shield) is required at 5 ft or deeper, with a competent-person inspection, egress within 25 ft, and spoil kept 2 ft from the edge (OSHA 1926 Subpart P).",
        keywords: &[
            "trench", "excavation", "excavate", "cave-in", "cave in", "shoring",
            "trench box", "shield", "sloping", "benching", "spoil", "underground",
        ],
        trades: &[],
    },
    Rule {
        code: "CAUGHT",
        title: "Caught-in / -between · rollover",
        rationale: "A caught-in/-between or rollover risk is described — confirm ROPS/seatbelt on equipment, clearance from fixed objects, and that no one was between moving and fixed points (OSHA Focus Four).",
        keywords: &[
            "pinned", "caught between", "crushed", "rollover", "tipped over",
            "overturned", "rops", "between the",
        ],
        trades: &[],
    },
    Rule {
        code: "STRUCT",
        title: "Steel erection / structural",
        rationale: "Structural steel / erection work is described — confirm connector fall protection, controlled decking zones, secured loads, and a qualified rigger/signal person for picks (OSHA 1926 Subpart R).",
        keywords: &[
            "steel erection", "girder", "rebar", "decking", "falsework", "formwork",
            "crane pick", "hoisting", "connector",
        ],
        trades: CIVIL,
    },
    Rule {
        code: "ELEC",
        title: "Electrocution / overhead lines",
        rationale: "Work near energized or overhead lines is described — confirm minimum approach distances, de-energizing/grounding, and equipment clearance from overhead power (OSHA 1926 Subpart K).",
        keywords: &[
            "overhead line", "power line", "energized", "live wire", "utility line", "boom near",
        ],
        trades: &[],
    },
];

/// Deterministic, offline scan over the narrative. Each matched rule yields one flag,
/// with the trade's OSHA citation + severity context attached when the trade is known.
/// Trade-scoped rules fire only when the record's trade NAICS matches.
pub fn scan(narrative: &str, trade_naics: Option<&str>) -> Vec<Flag> {
    let hay = narrative.to_lowercase();
    let ctx = trade_naics.and_then(cited_context);
    RULES
        .iter()
        .filter(|rule| {
            let trade_ok = rule.trades.is_empty()
                || trade_naics.is_some_and(|n| rule.trades.contains(&n));
            trade_ok && rule.keywords.iter().any(|k| hay.contains(k))
        })
        .map(|rule| Flag {
            code: rule.code.to_string(),
            title: rule.title.to_string(),
            rationale: rule.rationale.to_string(),
            osha_context: ctx.clone(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flags_fall_on_height_language() {
        let f = scan("We were up on the roof near the open edge all afternoon.", Some("238160"));
        assert!(f.iter().any(|x| x.code == "FALL"));
    }

    #[test]
    fn flags_missing_ppe() {
        let f = scan("One laborer had no hard hat on the deck.", None);
        assert!(f.iter().any(|x| x.code == "PPE"));
    }

    #[test]
    fn attaches_osha_context_for_known_trade() {
        let ctx = cited_context("238160").unwrap();
        assert!(ctx.contains("Roofing"));
        assert!(ctx.contains("57.6")); // matches data/osha_trade_stats.json (0.5764)
    }

    #[test]
    fn clean_narrative_yields_no_flags() {
        let f = scan("Poured the footing and packed up for the day.", Some("236220"));
        assert!(f.is_empty());
    }

    // ---- v2.2: highway/bridge rules ----
    #[test]
    fn flags_workzone_for_highway_trade() {
        let f = scan("Crew on the shoulder with a lane closure and a flagger.", Some("237310"));
        assert!(f.iter().any(|x| x.code == "WORKZONE"));
    }

    #[test]
    fn workzone_scoped_out_for_roofing() {
        let f = scan("Cones and traffic on the shoulder.", Some("238160"));
        assert!(!f.iter().any(|x| x.code == "WORKZONE"));
    }

    #[test]
    fn flags_trench_globally() {
        let f = scan("Open trench with no shoring today.", Some("238160"));
        assert!(f.iter().any(|x| x.code == "TRENCH"));
    }

    // ---- v2.2: severity (avg penalty when cited) surfaced, not just the rate ----
    #[test]
    fn severity_surfaced_in_context() {
        let ctx = cited_context("237310").unwrap();
        assert!(ctx.contains("41.1")); // cited rate
        assert!(ctx.contains("avg penalty")); // severity now surfaced
        assert!(ctx.contains("$21,7")); // ~$21,700 (avg_penalty_per_cited 21738 → nearest $100)
    }

    #[test]
    fn fmt_usd_rounds_and_groups() {
        assert_eq!(fmt_usd(21738.0), "$21,700");
        assert_eq!(fmt_usd(11653.0), "$11,700");
        assert_eq!(fmt_usd(950.0), "$1,000");
    }
}
