//! 04 Safety flags — deterministic, OFFLINE rules with OSHA trade context attached.
//! Rules-first by design (no LLM in the core loop). Flags ASSIST judgment — the user
//! accepts / dismisses / annotates each one. Biased toward recall (catching gaps).
use serde::Serialize;

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Flag {
    pub code: String,
    pub title: String,
    pub rationale: String,
    pub osha_context: Option<String>,
}

// OSHA trade stats generated by data/osha_pipeline.py (bundled, read fully offline).
const TRADE_STATS: &str = include_str!("../../data/osha_trade_stats.json");

/// "Roofing · 57.8% cited for this" — trade context for a flag, from the OSHA data spine.
pub fn cited_context(naics: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(TRADE_STATS).ok()?;
    let t = v.get("trades")?.get(naics)?;
    let name = t.get("name")?.as_str()?;
    let rate = t.get("cited_rate")?.as_f64()?;
    Some(format!("{name} · {:.1}% cited for this", rate * 100.0))
}

struct Rule {
    code: &'static str,
    title: &'static str,
    rationale: &'static str,
    keywords: &'static [&'static str],
}

const RULES: &[Rule] = &[
    Rule {
        code: "FALL",
        title: "Fall protection",
        rationale: "Work at height is described — confirm fall protection (harness/lanyard, guardrail, or net) was in place.",
        keywords: &[
            "roof", "rooftop", "ladder", "leading edge", "open edge", "off the edge",
            "height", "elevated", "second floor", "third floor", "no harness", "without a harness",
        ],
    },
    Rule {
        code: "PPE",
        title: "PPE",
        rationale: "A missing-PPE phrase was detected — confirm hard hat, eye protection, gloves, and hi-vis as required.",
        keywords: &[
            "no hard hat", "without a hard hat", "no helmet", "no gloves", "without gloves",
            "no goggles", "no glasses", "no eye protection", "no vest", "no hi-vis",
            "without ppe", "missing ppe",
        ],
    },
    Rule {
        code: "SCAF",
        title: "Scaffolding / guardrail",
        rationale: "Scaffolding is described — confirm guardrails, proper planking, and a competent-person inspection.",
        keywords: &["scaffold", "guardrail", "planking", "staging", "work platform"],
    },
];

/// Deterministic, offline scan over the narrative. Each matched rule yields one flag,
/// with the trade's OSHA citation context attached when the trade is known.
pub fn scan(narrative: &str, trade_naics: Option<&str>) -> Vec<Flag> {
    let hay = narrative.to_lowercase();
    let ctx = trade_naics.and_then(cited_context);
    RULES
        .iter()
        .filter(|rule| rule.keywords.iter().any(|k| hay.contains(k)))
        .map(|rule| Flag {
            code: rule.code.to_string(),
            title: rule.title.to_string(),
            rationale: rule.rationale.to_string(),
            osha_context: ctx.clone(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flags_fall_on_height_language() {
        let f = scan("We were up on the roof near the open edge all afternoon.", Some("238160"));
        assert!(f.iter().any(|x| x.code == "FALL"));
    }

    #[test]
    fn flags_missing_ppe() {
        let f = scan("One laborer had no hard hat on the deck.", None);
        assert!(f.iter().any(|x| x.code == "PPE"));
    }

    #[test]
    fn attaches_osha_context_for_known_trade() {
        let ctx = cited_context("238160").unwrap();
        assert!(ctx.contains("Roofing"));
        assert!(ctx.contains("57.6")); // matches data/osha_trade_stats.json (0.5764)
    }

    #[test]
    fn clean_narrative_yields_no_flags() {
        let f = scan("Poured the footing and packed up for the day.", Some("238160"));
        assert!(f.is_empty());
    }
}
